In [3]:
import numpy as np

In [44]:
A = np.array([[1,1,1,1],[2,2,2,2]])
B = np.array([[1,2,3,4],[1,1,1,1],[1,2,1,9]])

In [45]:
A

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [46]:
A.shape

(2, 4)

In [47]:
B

array([[1, 2, 3, 4],
       [1, 1, 1, 1],
       [1, 2, 1, 9]])

In [52]:
B.T

array([[1, 1, 1],
       [2, 1, 2],
       [3, 1, 1],
       [4, 1, 9]])

In [51]:
A.dot(B.T)

array([[10,  4, 13],
       [20,  8, 26]])

In [40]:
B.T

array([[1, 1, 1],
       [2, 1, 2],
       [3, 1, 1]])

In [41]:
A.dot(B.T)

array([[ 6,  3,  4],
       [12,  6,  8]])

In [61]:
print(A[:, np.newaxis, :])

[[[1 1 1 1]]

 [[2 2 2 2]]]


In [62]:
B

array([[1, 2, 3, 4],
       [1, 1, 1, 1],
       [1, 2, 1, 9]])

In [68]:
diff = A[:,np.newaxis,:] - B
diff #This is two arrays that can be indexed. 
#In[68]: diff.shape 
#out[69]: (2, 3, 4)

array([[[ 0, -1, -2, -3],
        [ 0,  0,  0,  0],
        [ 0, -1,  0, -8]],

       [[ 1,  0, -1, -2],
        [ 1,  1,  1,  1],
        [ 1,  0,  1, -7]]])

In [69]:
diff.shape

(2, 3, 4)

In [73]:
diff[0]

array([[ 0, -1, -2, -3],
       [ 0,  0,  0,  0],
       [ 0, -1,  0, -8]])

In [74]:
B

array([[1, 2, 3, 4],
       [1, 1, 1, 1],
       [1, 2, 1, 9]])

In [72]:
np.square(diff[0] - B) #Square of the differences between diff[0] and B

array([[  1,   9,  25,  49],
       [  1,   1,   1,   1],
       [  1,   9,   1, 289]])

In [75]:
np.square(diff[1] - B) #Square of the differences between diff[1] and B

array([[  0,   4,  16,  36],
       [  0,   0,   0,   0],
       [  0,   4,   0, 256]])

In [82]:
diff = A[:,np.newaxis,:] - B
diff #This is two arrays that can be indexed. 
#In[68]: diff.shape 
#out[69]: (2, 3, 4)

array([[[ 0, -1, -2, -3],
        [ 0,  0,  0,  0],
        [ 0, -1,  0, -8]],

       [[ 1,  0, -1, -2],
        [ 1,  1,  1,  1],
        [ 1,  0,  1, -7]]])

In [81]:
np.square(A[:,np.newaxis,:] - B) #Square each element in both arrays from above. 

array([[[ 0,  1,  4,  9],
        [ 0,  0,  0,  0],
        [ 0,  1,  0, 64]],

       [[ 1,  0,  1,  4],
        [ 1,  1,  1,  1],
        [ 1,  0,  1, 49]]])

In [85]:
np.sum(np.square(A[:,np.newaxis,:] - B), axis=1) #Sum along row element-wise.

array([[ 0,  2,  4, 73],
       [ 3,  1,  3, 54]])

In [86]:
np.sum(np.square(A[:,np.newaxis,:] - B), axis=0) #Sum along column element-wise.

array([[  1,   1,   5,  13],
       [  1,   1,   1,   1],
       [  1,   1,   1, 113]])

In [87]:
np.sum(np.square(A[:,np.newaxis,:] - B), axis=2) #Each row in the first array becomes an element in the result.

array([[14,  0, 65],
       [ 6,  4, 51]])

In [130]:
[(0 + 1 + 4 + 9), (0 + 0 + 0 + 0), (0 + 1 + 0 + 64)], [(1 + 0 + 1 + 4), (1 + 1 + 1 + 1), (1 + 0 + 1 + 49)]

([14, 0, 65], [6, 4, 51])

In [138]:
np.sqrt(np.array([(0 + 1 + 4 + 9), (0 + 0 + 0 + 0), (0 + 1 + 0 + 64)]))

array([3.74165739, 0.        , 8.06225775])

In [137]:
np.sqrt(np.array([(1 + 0 + 1 + 4), (1 + 1 + 1 + 1), (1 + 0 + 1 + 49)]))

array([2.44948974, 2.        , 7.14142843])

In [139]:
np.sqrt(np.sum(np.square(A[:,np.newaxis,:] - B), axis=2) )

array([[3.74165739, 0.        , 8.06225775],
       [2.44948974, 2.        , 7.14142843]])

In [141]:
np.sum(np.square(A)[:,np.newaxis,:], axis=2)

array([[ 4],
       [16]])

In [142]:
2 * A.dot(B.T)

array([[20,  8, 26],
       [40, 16, 52]])

In [143]:
np.sum(np.square(B), axis=1) #Check

array([30,  4, 87])

In [147]:
np.sum(np.square(B), axis=1)

array([30,  4, 87])

In [148]:
np.square(B)

array([[ 1,  4,  9, 16],
       [ 1,  1,  1,  1],
       [ 1,  4,  1, 81]])

In [149]:
np.square(A)[:,np.newaxis,:]

array([[[1, 1, 1, 1]],

       [[4, 4, 4, 4]]])

In [150]:
np.sum(np.square(A)[:,np.newaxis,:], axis=2)

array([[ 4],
       [16]])

In [151]:
np.square(A)

array([[1, 1, 1, 1],
       [4, 4, 4, 4]])

In [93]:
np.sqrt(np.sum(np.square(A[:,np.newaxis,:] - B), axis=2)) #Take square root of each element.

array([[3.74165739, 0.        , 8.06225775],
       [2.44948974, 2.        , 7.14142843]])

In [103]:
np.array([np.sqrt(14), np.sqrt(0), np.sqrt(65)]), np.array([np.sqrt(6), np.sqrt(4), np.sqrt(51)])

(array([3.74165739, 0.        , 8.06225775]),
 array([2.44948974, 2.        , 7.14142843]))

In [ ]:
# Let's experiment with 3-d array.    
In [5]: x = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
In [6]: x
Out[6]: 
array([[[1, 2],
        [3, 4]],
       [[1, 2],
        [3, 4]]])
In [7]: x.shape
Out[7]: (2, 2, 2)
In [8]: x[0]        # axis-0
Out[8]: 
array([[1, 2],
       [3, 4]])
In [9]: x[1]        # still axis-0
Out[9]: 
array([[1, 2],
       [3, 4]])
In [10]: x[0][0]    # axis-1
Out[10]: array([1, 2])
In [11]: x[0][0][0] # axis-2
Out[11]: 1
In [12]: np.sum(x, axis=0)  # Notice that it eliminated the specified axis.
Out[12]: 
array([[2, 4],
       [6, 8]])
In [13]: np.sum(x, axis=1)
Out[13]: 
array([[4, 6],
       [4, 6]])
In [14]: np.sum(x, axis=2)
Out[14]: 
array([[3, 7],
       [3, 7]])

In [112]:
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [113]:
x[0]

array([[1, 2],
       [3, 4]])

In [114]:
x[0][0]

array([1, 2])

In [115]:
x[0][0][0]

1

In [116]:
np.sum(x, axis=2)

array([[ 3,  7],
       [11, 15]])

In [152]:
#First, learn the syntax of np.sum(mat, axis=0, 1, 2) 
#Second, learn the need to use `[:, np.newaxis, :]`
#Thrid, learn how all of this is used in NumPy broadcasting.
#Forth, learn how to replace loops with vectors using broadcasting. 

#https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/
#https://medium.com/@aerinykim/numpy-sum-axis-intuition-6eb94926a5d1
#https://stackoverflow.com/questions/27948363/numpy-broadcast-to-perform-euclidean-distance-vectorized/37903795#37903795